- name: check if BOTSv2 attack only app exists
  stat:
    path: /opt/splunk/etc/apps/botsv2_data_set
  register: botsv2a_app

# - name: download BOTSv2 attack only dataset
#   unarchive:
#     src: 'https://s3.amazonaws.com/botsdataset/botsv2/botsv2_data_set_attack_only.tgz'
#     dest: /opt/splunk/etc/apps 
#     owner: splunk
#     group: splunk
#     remote_src: yes
#   when: botsv2a_app.stat.exists == False


- name: Create the /opt/splunk/tmp/ directory
  file:
    path: "/opt/splunk/tmp"
    state: directory
    group: "splunk"
    owner: "splunk"
  become: yes

- name: Copy BOTSv2 attack only dataset from local to Splunk Server
  copy:
    src: "{{ local_downloads_folder }}/botsv2_data_set_attack_only.tgz"
    dest: /opt/splunk/tmp/botsv1-attack-only.tgz  
    force: no

- name: unarchive BOTSv2 attack only dataset
  unarchive:
    src: '/opt/splunk/tmp/botsv2_data_set_attack_only.tgz'    
    dest: /opt/splunk/etc/apps 
    owner: splunk
    group: splunk
    remote_src: yes
  when: botsv1a_app.stat.exists == False

