
- name: check if BOTSv1 app exists
  stat:
    path: /opt/splunk/etc/apps/botsv1_data_set
  register: botsv1_app

# - name: download BOTSv1 dataset
#   unarchive:
#     src: 'https://s3.amazonaws.com/botsdataset/botsv1/splunk-pre-indexed/botsv1_data_set.tgz'
#     dest: /opt/splunk/etc/apps 
#     owner: splunk
#     group: splunk
#     remote_src: yes
#   when: botsv1_app.stat.exists == False

# localize

- name: Create the /opt/splunk/tmp/ directory
  file:
    path: "/opt/splunk/tmp"
    state: directory
    group: "splunk"
    owner: "splunk"
  become: yes

- name: Copy BOTSv1 dataset from local to Splunk Server
  copy:
    src: "{{ local_downloads_folder }}/botsv1_data_set.tgz"
    dest: /opt/splunk/tmp/botsv1_data_set.tgz
    force: no
  when: botsv1_app.stat.exists == False

- name: unarchive BOTSv1 dataset
  unarchive:
    src: '/opt/splunk/tmp/botsv1_data_set.tgz'    
    dest: /opt/splunk/etc/apps 
    owner: splunk
    group: splunk
    remote_src: yes
  when: botsv1a_app.stat.exists == False

